### ISSUE TITLE
Arch Linux logo

### ISSUE THREAD

**Issue by graysky2** [christopherdumas/Bike#19]
Nice rip-off of the Arch Linux logo on your main page.

**Comment by phrakture** [comment]
Hello Christopher,

I apologize for contacting you in so public a manner, but you have left no easy way to contact you anywhere.

My name is Aaron Griffin, and I am the trademark holder for the Arch Linux project. You are using a variation on our logo in your page that is not permitted under our [trademark policy](https://wiki.archlinux.org/index.php/DeveloperWiki:TrademarkPolicy).

Please remove the logo from your page.

Cheers,
Aaron

**Comment by christopherdumas** [comment]
I apologize. this was not intended, i was looking for an official C logo, and found that on google images. I was in a hurry. currently i am having some technical issues with the website, but as soon as they have been mitigated, i will comply.

**Comment by tech4david** [comment]
Next time you search for "c language logo" do it from [here](http://search.creativecommons.org/) rather than from Google Images ;)
